### ISSUE TITLE
lima の設定

### ISSUE THREAD

**Issue by gotokazuki** [gotokazuki/dotfiles#31]
設定ファイルを管理するようにしたい

また、 lima だと mysql docker image が動かないっぽい
mariadb で代用する感じになりそう

**Comment by gotooooo** [comment]
初回の limactl start が失敗する問題も調査する

**Comment by gotooooo** [comment]
nerdctl か docker かどちらが良い？
docker で良さそうな気はする

**Comment by gotooooo** [comment]
mysql はこれで問題なし https://hub.docker.com/r/arm64v8/mysql/
lima を使う場合、 volumes は docker compose のグローバルで指定すると良い
lima の writable のディレクトリを指定してもうまくいかなかった

**Comment by gotokazuki** [comment]
rancher desktop が使えるので lima は dotfiles から削除する
