### ISSUE TITLE
入力ソース

### ISSUE THREAD

**Issue by gotokazuki** [gotokazuki/dotfiles#43]
caps lock で入力ソース切り替えを有効にする

ctrl+cmd の場合、離すタイミング？によって切り替わらないことが多い

**Comment by gotooooo** [comment]
google 日本語入力だと切り替えられないので https://karabiner-elements.pqrs.org/ を使う

**Comment by gotooooo** [comment]
```
brew install karabiner-elements
```

**Comment by gotokazuki** [comment]
対応しない
